# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 05:39

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0155_change_default_realm_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('create_time', models.PositiveIntegerField()),
                ('over_time', models.PositiveIntegerField()),
                ('task', models.CharField(max_length=60)),
                ('task_details', models.CharField(max_length=300, null=True)),
                ('state', models.IntegerField(default=2)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BacklogAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_url', models.CharField(default='', max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
                ('backlog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Backlog')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('generate_time', models.PositiveIntegerField()),
                ('accomplish', models.CharField(max_length=700)),
                ('overdue', models.CharField(max_length=400, null=True)),
                ('underway', models.CharField(max_length=400, null=True)),
                ('types', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StatementAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_accessory_url', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
                ('Statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='StatementBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlog_id', models.PositiveIntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='StatementState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=300)),
                ('state', models.BooleanField(default=False)),
                ('statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Statement')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_backlog', models.CharField(max_length=60)),
                ('backlog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Backlog')),
            ],
        ),
    ]
