# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0156_backlog_backlogaccessory_statement_statementaccessory_statementbacklog_updatebacklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatebacklog',
            name='update_time',
        ),
    ]
