# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0156_backlog_backlogaccessory_statement_statementaccessory_statementbacklog_statementstate_updatebacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.CharField(max_length=80),
        ),
    ]
