# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0156_backlog_backlogaccessory_statement_statementaccessory_statementbacklog_statementstate_updatebacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogaccessory',
            name='accessory_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='statementaccessory',
            name='accessory_size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
