# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0157_auto_20180622_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementaccessory',
            name='accessory_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='statementaccessory',
            name='accessory_size',
            field=models.CharField(default='', max_length=30),
        ),
    ]
