# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import zerver.models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0157_remove_updatebacklog_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatebacklog',
            name='backlog_id',
            field=models.PositiveIntegerField(verbose_name=zerver.models.Backlog),
        ),
    ]
