# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0158_auto_20180705_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_user_id', models.PositiveIntegerField(null=True)),
                ('reply_type', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=120)),
                ('from_uid', models.PositiveIntegerField()),
                ('reply_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZgStatementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.PositiveIntegerField()),
                ('topic_type', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=120)),
                ('from_uid', models.PositiveIntegerField()),
                ('comment_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='zgreplycomment',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.ZgStatementComment'),
        ),
    ]
