# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0159_auto_20180611_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.CharField(max_length=80),
        ),
    ]
