# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0160_auto_20180612_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementaccessory',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
