# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0161_auto_20180717_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='task_details',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='updatebacklog',
            name='update_backlog',
            field=models.CharField(max_length=230),
        ),
    ]
