# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0161_statementaccessory_is_delete'),
        ('zerver', '0160_auto_20180613_1420'),
    ]

    operations = [
    ]
