# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0163_remove_zgoutsidework_sign_off_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20)),
                ('table_id', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=120)),
                ('feedback_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZgLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20, null=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('count', models.CharField(max_length=10)),
                ('cause', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='发起申请', max_length=15)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZgReimburse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=240, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='发起申请', max_length=25)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZgReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user_id', models.CharField(max_length=10)),
                ('types', models.CharField(max_length=30)),
                ('table_id', models.PositiveIntegerField()),
                ('status', models.CharField(default='审批中', max_length=15)),
                ('duties', models.CharField(default='approval', max_length=30)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
