# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-27 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0166_auto_20180823_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=30)),
                ('type_id', models.IntegerField()),
                ('collection_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
