# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-12 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0171_zgdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgdepartment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
