# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0173_userprofile_zg_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgattendance',
            name='sign_in_explain',
            field=models.CharField(max_length=15, null=True, verbose_name='打卡备注'),
        ),
        migrations.AlterField(
            model_name='zgattendance',
            name='sign_in_time',
            field=models.DateTimeField(null=True, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='zgattendance',
            name='sign_off_explain',
            field=models.CharField(max_length=15, null=True, verbose_name='打卡备注'),
        ),
        migrations.AlterField(
            model_name='zgattendance',
            name='sign_off_time',
            field=models.DateTimeField(null=True, verbose_name='下班时间'),
        ),
    ]
