# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0174_auto_20180913_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgattendance',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
