# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0176_auto_20181010_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgCorrectzAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.PositiveIntegerField()),
                ('correctz_type', models.CharField(max_length=32)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerver.Attachment')),
            ],
        ),
        migrations.RemoveField(
            model_name='zgleave',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='zgreimburse',
            name='image_url',
        ),
    ]
