# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0177_auto_20181010_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgclouddisk',
            name='types',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
