# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-22 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0178_zgreview_is_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='atendance_type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
