# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0178_zgclouddisk_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zgclouddisk',
            name='types',
        ),
    ]
