# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0179_userprofile_atendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgdepartmentattendance',
            name='department',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
