# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-23 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0180_zgdepartmentattendance_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgWorkNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(max_length=16)),
                ('stair', models.CharField(max_length=150)),
                ('second', models.CharField(max_length=150)),
                ('third', models.CharField(max_length=150)),
                ('send_time', models.CharField(max_length=64)),
                ('table_type', models.CharField(max_length=16)),
                ('table_id', models.CharField(max_length=16)),
                ('table_state', models.CharField(max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
