# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-24 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0181_zgworknotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPlease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256)),
                ('urgency_degree', models.CharField(max_length=18)),
                ('jobs_date', models.DateField(null=True)),
                ('content', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(default='发起申请', max_length=25)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('happening', models.CharField(max_length=512)),
                ('quality', models.CharField(max_length=18)),
                ('issue', models.CharField(max_length=512, null=True)),
                ('scheme', models.CharField(max_length=512, null=True)),
                ('worker_improve', models.CharField(max_length=512, null=True)),
                ('coordinate_department', models.CharField(max_length=128, null=True)),
                ('complete_time', models.DateField()),
                ('remark', models.CharField(max_length=512, null=True)),
                ('status', models.CharField(default='发起申请', max_length=25)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZgPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256)),
                ('puchase_date', models.DateField()),
                ('goods_name', models.CharField(max_length=64)),
                ('specification', models.CharField(max_length=64, null=True)),
                ('count', models.PositiveIntegerField()),
                ('total_prices', models.IntegerField()),
                ('status', models.CharField(default='发起申请', max_length=25)),
                ('send_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
