# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0182_jobsplease_projectprogress_zgpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgpurchase',
            name='unit_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
